version: '3.6'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    ports:
      - 9300:9300
      - 9200:9200
    environment:
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-methods=OPTIONS, HEAD, GET, POST, PUT, DELETE
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type, Content-Length
      - transport.host=127.0.0.1
      - cluster.name=angular-cluster-example
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - angular_elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - angular_elasticsearch_network
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    ports:
      - 5601:5601
    networks:
      - angular_elasticsearch_network
volumes:
  angular_elasticsearch_data:
networks:
  angular_elasticsearch_network:
